// Файл: src/lib/serviceCitySlugs.ts
// Автогенерируется из существующих маршрутов src/app/services/{izn,imz,les}/<slug>/page.tsx.
// Используется ТОЛЬКО для карты сайта (sitemap.ts), чтобы городские лендинги
// попадали в индекс. Никакой логики рендера/дизайна здесь нет.
// izn — инвентаризация зелёных насаждений, imz — инвентаризация мест захоронений,
// les — лесоустройство.

export const IZN_CITY_SLUGS: string[] = [
  'abakan', 'almetevsk', 'angarsk', 'arhangelsk', 'armavir', 'artyom',
  'arzamas', 'astrahan', 'balakovo', 'balashiha', 'barnaul', 'batajsk',
  'belgorod', 'berdsk', 'berezniki', 'bijsk', 'blagoveshchensk', 'bratsk',
  'bryansk', 'cheboksary', 'chelyabinsk', 'cherepovec', 'chita', 'derbent',
  'dimitrovgrad', 'dolgoprudnyj', 'domodedovo', 'dzerzhinsk', 'ekaterinburg', 'elektrostal',
  'elista', 'engels', 'essentuki', 'evpatoriya', 'groznyj', 'habarovsk',
  'hanty-mansijsk', 'hasavyurt', 'himki', 'irkutsk', 'ivanovo', 'izhevsk',
  'joshkar-ola', 'kaliningrad', 'kaluga', 'kamensk-uralskij', 'kamyshin', 'kaspijsk',
  'kazan', 'kemerovo', 'kerch', 'kirov', 'kislovodsk', 'kolomna',
  'komsomolsk-na-amure', 'kopejsk', 'korolyov', 'kostroma', 'kovrov', 'krasnodar',
  'krasnogorsk', 'krasnoyarsk', 'kurgan', 'kursk', 'kyzyl', 'lipeck',
  'lyubercy', 'magnitogorsk', 'mahachkala', 'majkop', 'miass', 'moskva',
  'murino', 'murmansk', 'murom', 'mytishchi', 'naberezhnye-chelny', 'nahodka',
  'nalchik', 'nazran', 'neftekamsk', 'nefteyugansk', 'nevinnomyssk', 'nizhnekamsk',
  'nizhnevartovsk', 'nizhnij-novgorod', 'nizhnij-tagil', 'noginsk', 'norilsk', 'novocheboksarsk',
  'novocherkassk', 'novokuzneck', 'novorossijsk', 'novoshahtinsk', 'novosibirsk', 'novyj-urengoj',
  'noyabrsk', 'obninsk', 'odincovo', 'oktyabrskij', 'omsk', 'orekhovo-zuevo',
  'orenburg', 'orsk', 'oryol', 'penza', 'perm', 'pervouralsk',
  'petropavlovsk-kamchatskij', 'petrozavodsk', 'podolsk', 'prokopevsk', 'pskov', 'pushkino',
  'pyatigorsk', 'ramenskoe', 'rostov-na-donu', 'ryazan', 'rybinsk', 'salavat',
  'samara', 'sankt-peterburg', 'saransk', 'saratov', 'serpuhov', 'sevastopol',
  'severodvinsk', 'seversk', 'shahty', 'shchyolkovo', 'simferopol', 'smolensk',
  'sochi', 'staryj-oskol', 'stavropol', 'sterlitamak', 'surgut', 'syktyvkar',
  'syzran', 'taganrog', 'tambov', 'tolyatti', 'tomsk', 'tula',
  'tver', 'tyumen', 'ufa', 'ulan-ude', 'ulyanovsk', 'ussurijsk',
  'velikij-novgorod', 'vidnoe', 'vladikavkaz', 'vladimir', 'vladivostok', 'volgodonsk',
  'volgograd', 'vologda', 'volzhskij', 'voronezh', 'yakutsk', 'yaroslavl',
  'yuzhno-sahalinsk', 'zhukovskij', 'zlatoust',
]

export const IMZ_CITY_SLUGS: string[] = [
  'abakan', 'almetevsk', 'angarsk', 'arhangelsk', 'armavir', 'artyom',
  'arzamas', 'astrahan', 'balashiha', 'barnaul', 'batajsk', 'belgorod',
  'berdsk', 'berezniki', 'bijsk', 'blagoveshchensk', 'bratsk', 'bryansk',
  'cheboksary', 'chelyabinsk', 'cherepovec', 'cherkessk', 'chita', 'derbent',
  'dimitrovgrad', 'dolgoprudnyj', 'domodedovo', 'dzerzhinsk', 'ekaterinburg', 'elektrostal',
  'elista', 'engels', 'essentuki', 'evpatoriya', 'groznyj', 'habarovsk',
  'hanty-mansijsk', 'hasavyurt', 'himki', 'irkutsk', 'ivanovo', 'izhevsk',
  'joshkar-ola', 'kaliningrad', 'kaluga', 'kamensk-uralskij', 'kamyshin', 'kaspijsk',
  'kazan', 'kemerovo', 'kerch', 'kirov', 'kislovodsk', 'kolomna',
  'komsomolsk-na-amure', 'kopejsk', 'korolyov', 'kostroma', 'kovrov', 'krasnodar',
  'krasnogorsk', 'krasnoyarsk', 'kurgan', 'kursk', 'kyzyl', 'lipeck',
  'lyubercy', 'magnitogorsk', 'mahachkala', 'majkop', 'miass', 'mihajlovsk',
  'moskva', 'murino', 'murmansk', 'murom', 'mytishchi', 'naberezhnye-chelny',
  'nahodka', 'nalchik', 'nazran', 'neftekamsk', 'nefteyugansk', 'nevinnomyssk',
  'nizhnekamsk', 'nizhnevartovsk', 'nizhnij-novgorod', 'nizhnij-tagil', 'noginsk', 'norilsk',
  'novocherkassk', 'novokuzneck', 'novomoskovsk', 'novoshahtinsk', 'novosibirsk', 'noyabrsk',
  'obninsk', 'odincovo', 'oktyabrskij', 'omsk', 'orekhovo-zuevo', 'orenburg',
  'orsk', 'oryol', 'penza', 'perm', 'pervouralsk', 'petropavlovsk-kamchatskij',
  'petrozavodsk', 'podolsk', 'prokopevsk', 'pskov', 'pushkino', 'pyatigorsk',
  'ramenskoe', 'reutov', 'rostov-na-donu', 'rubcovsk', 'ryazan', 'rybinsk',
  'salavat', 'samara', 'sankt-peterburg', 'saransk', 'saratov', 'serpuhov',
  'sevastopol', 'severodvinsk', 'seversk', 'shahty', 'shchyolkovo', 'simferopol',
  'smolensk', 'sochi', 'staryj-oskol', 'stavropol', 'sterlitamak', 'surgut',
  'syktyvkar', 'syzran', 'taganrog', 'tambov', 'tolyatti', 'tomsk',
  'tula', 'tver', 'tyumen', 'ufa', 'ulan-ude', 'ulyanovsk',
  'ussurijsk', 'velikij-novgorod', 'vidnoe', 'vladikavkaz', 'vladimir', 'vladivostok',
  'volgodonsk', 'volgograd', 'vologda', 'volzhskij', 'voronezh', 'yakutsk',
  'yaroslavl', 'yuzhno-sahalinsk', 'zhukovskij', 'zlatoust',
]

export const LES_CITY_SLUGS: string[] = [
  'abakan', 'almetevsk', 'angarsk', 'arhangelsk', 'armavir', 'artyom',
  'arzamas', 'astrahan', 'balakovo', 'balashiha', 'barnaul', 'batajsk',
  'belgorod', 'berdsk', 'berezniki', 'bijsk', 'blagoveshchensk', 'bratsk',
  'bryansk', 'cheboksary', 'chelyabinsk', 'cherepovec', 'chita', 'derbent',
  'dimitrovgrad', 'dolgoprudnyj', 'domodedovo', 'dzerzhinsk', 'ekaterinburg', 'elektrostal',
  'elista', 'engels', 'essentuki', 'evpatoriya', 'groznyj', 'habarovsk',
  'hanty-mansijsk', 'hasavyurt', 'himki', 'irkutsk', 'ivanovo', 'izhevsk',
  'joshkar-ola', 'kaliningrad', 'kaluga', 'kamensk-uralskij', 'kamyshin', 'kaspijsk',
  'kazan', 'kemerovo', 'kerch', 'kirov', 'kislovodsk', 'kolomna',
  'komsomolsk-na-amure', 'kopejsk', 'korolyov', 'kostroma', 'kovrov', 'krasnodar',
  'krasnogorsk', 'krasnoyarsk', 'kurgan', 'kursk', 'kyzyl', 'lipeck',
  'lyubercy', 'magnitogorsk', 'mahachkala', 'majkop', 'miass', 'moskva',
  'murino', 'murmansk', 'murom', 'mytishchi', 'naberezhnye-chelny', 'nahodka',
  'nalchik', 'nazran', 'neftekamsk', 'nefteyugansk', 'nevinnomyssk', 'nizhnekamsk',
  'nizhnevartovsk', 'nizhnij-novgorod', 'nizhnij-tagil', 'noginsk', 'norilsk', 'novocheboksarsk',
  'novocherkassk', 'novokuzneck', 'novorossijsk', 'novoshahtinsk', 'novosibirsk', 'novyj-urengoj',
  'noyabrsk', 'obninsk', 'odincovo', 'oktyabrskij', 'omsk', 'orekhovo-zuevo',
  'orenburg', 'orsk', 'oryol', 'penza', 'perm', 'pervouralsk',
  'petropavlovsk-kamchatskij', 'petrozavodsk', 'podolsk', 'prokopevsk', 'pskov', 'pushkino',
  'pyatigorsk', 'ramenskoe', 'rostov-na-donu', 'ryazan', 'rybinsk', 'salavat',
  'samara', 'sankt-peterburg', 'saransk', 'saratov', 'serpuhov', 'sevastopol',
  'severodvinsk', 'seversk', 'shahty', 'shchyolkovo', 'simferopol', 'smolensk',
  'sochi', 'staryj-oskol', 'stavropol', 'sterlitamak', 'surgut', 'syktyvkar',
  'syzran', 'taganrog', 'tambov', 'tolyatti', 'tomsk', 'tula',
  'tver', 'tyumen', 'ufa', 'ulan-ude', 'ulyanovsk', 'ussurijsk',
  'velikij-novgorod', 'vidnoe', 'vladikavkaz', 'vladimir', 'vladivostok', 'volgodonsk',
  'volgograd', 'vologda', 'volzhskij', 'voronezh', 'yakutsk', 'yaroslavl',
  'yuzhno-sahalinsk', 'zhukovskij', 'zlatoust',
]
